services:
  cm-catalog:
    platform: linux/x86_64
    container_name: rae-cm-catalog
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/usr/src/app/
      - /usr/src/app/node_modules
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    command: yarn run start:dev
    env_file:
      - .env
    depends_on:
      - mysql
  mysql:
    platform: linux/x86_64
    container_name: rae-cm-catalog-mysql
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_HOST: ${DB_HOST}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - rae-cm-catalog-database:/var/lib/mysql
volumes:
  rae-cm-catalog-database:
